kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vault
  namespace: vault
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
