name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: trevorbox/github-workflows-operators/.github/workflows/pr-operator.yml@main
    with: 
      TEST_TARGETS: "test integration"